import React from "react";
import Nav from "./Nav";
import Wrapper, { WrapperVariant } from "./Wrapper";
import Head from "next/head";

interface Props {
  children?: JSX.Element | JSX.Element[];
  variant?: WrapperVariant;
}

const Layout = ({ children, variant }: Props) => {
  return (
    <>
      <Head>
        <title>Barber Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav pageProps={undefined} />
      <Wrapper variant={variant}>{children}</Wrapper>
    </>
  );
};

export default Layout;
